### ISSUE TITLE
Plus d'affichage depuis mise à jour

### ISSUE THREAD

**Issue by TiphTech** [Salvialf/JEEDOM-Widget-SliderButton#1]
Je n'ai malheureusement plus d'affichage du widget depuis la dernière mise à jour (avant hier) j'ai réinstaller à nouveau avec pimp my jeedom ou manuellement en copiant les fichiers dans data/customTemplates/ , rien n'y fait
J'ai l'erreur (dans jeedom): jeedom SyntaxError: Unexpected identifier 'consigne' ligne 3
Jeedom V4.2.7 (stable)
Merci
<img width="163" alt="Capture d’écran 2022-02-02 à 14 48 39" src="https://user-images.githubusercontent.com/77073571/152167225-80906da5-f366-4201-ba35-ad8f70a70ac2.png">

**Comment by TiphTech** [comment]
L'ancienne version est disponible quelque part? pour essayer

**Comment by Salvialf** [comment]
...Tout de suite "l'ancienne version" j'aime cette façon de réagir...

Déjà on ne met pas des commandes seules sur un design normalement mais l'équipement entier. Le curseur a besoin de l'info pour fonctionner.
De 2 ça a été corrigé hier soir !

C'est sûr que ton message est d'une grande aide pour la communauté en tout cas : ça marche plus chez moi vite la version d'avant...

**Comment by TiphTech** [comment]
t'excite pas comme ça je demande l'ancienne version pour confirmer que c'est ton plugin mal codé qui ne fonctionne plus ou la MAJ jeedom qui a été faite en même temps
Si ça été corrigé hier soir je pense donc avoir aidé la communauté ;-)

**Comment by Salvialf** [comment]
mon plugin mal codé ?

Et non c'est un vrai utilisateur sur le forum qui a fait avancer la communauté certainement pas quelqu'un qui a le nez dans son nombril !
